<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $positions = [
            'Dokter',
            'Perawat',
            'Bidan',
            'Farmasis',
            'Radiografer',
            'Analis Laboratorium',
            'Administrator',
        ];

        $departments = [
            'Poliklinik Umum',
            'Ruang Rawat Inap',
            'IGD',
            'Laboratorium',
            'Radiologi',
            'Farmasi',
            'Administrasi',
        ];

        // Create 10 users and corresponding employees
        User::factory()
            ->count(10)
            ->create()
            ->each(function (User $user, $index) use ($positions, $departments) {
                $employeeCode = 'EMP' . str_pad($user->id, 4, '0', STR_PAD_LEFT);

                $user->employee()->create([
                    'uuid' => null, // will be generated by model boot
                    'employee_code' => $employeeCode,
                    'name' => $user->name,
                    'photo' => null,
                    'position' => $positions[array_rand($positions)],
                    'department' => $departments[array_rand($departments)],
                    'is_active' => true,
                ]);
                $user->assignRole('karyawan');
            });
    }
}
