<?php

namespace Database\Seeders;

use App\Models\Employee;
use App\Models\Position;
use App\Models\Unit;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class EmployeeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $positions = Position::pluck('id', 'name')->toArray();

        $departments = Unit::pluck('id', 'name')->toArray();

        // Create 10 users and corresponding employees
        User::factory()
            ->count(10)
            ->create()
            ->each(function (User $user) use ($positions, $departments) {
                $employeeCode = 'EMP' . str_pad($user->id, 4, '0', STR_PAD_LEFT);

                $user->employee()->create([
                    'uuid' => null, // will be generated by model boot
                    'employee_code' => $employeeCode,
                    'name' => $user->name,
                    'photo' => null,
                    'position_id' => $positions[array_rand($positions)],
                    'unit_id' => $positions[array_rand($positions)],
                    'is_active' => true,
                ]);
                $user->assignRole('karyawan');
            });
    }
}
